name: SonarCloud Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: hAver02
          projectKey: hAver02
          token: ${{ secrets.SONAR_TOKEN }}
